routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostCategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['middleware' => 'auth'], function (){
    Route::resource('posts', PostController::class);
    Route::resource('post-categories', PostCategoryController::class);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/PostCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PostCategory extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];

    public function post()
    {
        return $this->hasOne(Post::class, 'id_category');
    }
}

app/Http/Controllers/PostCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\PostCategory;

class PostCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post_categories = PostCategory::all();

        return view('post_categories.index', compact('post_categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post_categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        PostCategory::create($request->all());

        return redirect()   ->route('post-categories.index')
                            ->with('success', 'Data berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post_category = PostCategory::findOrFail($id);
        
        return view('post_categories.show', compact('post_category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(PostCategory $post_category)
    {
        return view('post_categories.edit', compact('post_category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post_categories = PostCategory::findOrFail($id);

        $post_categories->update($request->all());

        return redirect()   ->route('post-categories.index')
                            ->with('success', 'Data berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(PostCategory $post_category)
    {
        $post_category->delete();
        
        return redirect()   ->route('post-categories.index')
                            ->with('success', 'Data berhasil dihapus');
    }
}

resources/views/post_categories/create.blade.php
@extends('layouts.app')

@section('content')
<h1>Tambah Artikel</h1>
<form action="{{ route('post-categories.store') }}" method="POST">
@csrf
  <div class="form-group">
    <label for="name">Judul</label>
    <input type="text" class="form-control" id="name" name="name">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

resources/views/post_categories/edit.blade.php
@extends('layouts.app')

@section('content')
<h1>Tambah Artikel</h1>
<form action="{{ route('post-categories.update', $post_category->id) }}" method="POST">
@csrf
@method('PUT')
  <div class="form-group">
    <label for="name">Judul</label>
    <input type="text" class="form-control" id="name" name="name" value="{{ $post_category->name  }}">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

resources/views/post_categories/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>Tabel Kategori Artikel</h1>
    @if($message = Session::get('success'))
    <div class="alert alert-success" role="alert">
        {{$message}}
    </div>
    @endif
    <a href="{{ route('post-categories.create') }}"><button type="button" class="btn btn-primary">Tambah Kategori</button></a>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Kategori</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($post_categories as $post_category)
                <tr>
                    <td>{{$post_category->id}}</td>
                    <td>{{$post_category->name}}</td>
                    <td>
                        <form action="{{route('post-categories.destroy', $post_category->id)}}" method="POST">
                            <a href="{{route('post-categories.show', $post_category->id)}}" class="btn btn-success">Show</a>
                            <a href="{{route('post-categories.edit', $post_category->id)}}" class="btn btn-warning">Edit</a>
                            
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/post_categories/show.blade.php
@extends('layouts.app')

@section('content')
<h1>{{ $post_category->id }}</h1>
<p>{{ $post_category->name }}</p>
@endsection